services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping", "-q"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - hzz_net

  coordinator:
    build: ./coordinator
    container_name: coordinator
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RESULTS_DIR=/results
    volumes:
      - results_vol:/results
    networks:
      - hzz_net
    restart: "no"

  worker:
    build: ./worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - hzz_net
    restart: on-failure

volumes:
  results_vol:

networks:
  hzz_net:
    driver: bridge
